-- Phase 1 of the Gamma enrichment pipeline.
-- Run this file before sql/03_mv2_gamma_enriched_draft.sql so the canonical
-- latest-by-conditionId Gamma relation exists before any token normalization or
-- order enrichment starts.
--
-- Raw Polymarket Gamma markets changelog over the current warpstream topic.
-- Field list is based on live samples from demo_pm_gamma_markets.
-- Protected upstream source topic: never delete, truncate, or repurpose
-- demo_pm_gamma_markets from this project.
--
-- Important: this raw-topic relation preserves the source JSON field names
-- exactly, including case. Any snake_case cleanup should happen in a derived
-- relation, not here.

USE DATABASE polymarket;
USE SCHEMA public;

CREATE CHANGELOG polymarket.public.pm_gamma_markets_cl (
  id STRING,
  question STRING,
  "conditionId" STRING,
  slug STRING,
  "resolutionSource" STRING,
  "endDate" STRING,
  liquidity STRING,
  "startDate" STRING,
  image STRING,
  icon STRING,
  "description" STRING,
  outcomes STRING,
  "outcomePrices" STRING,
  volume STRING,
  active BOOLEAN,
  closed BOOLEAN,
  "marketMakerAddress" STRING,
  "createdAt" STRING,
  "updatedAt" STRING,
  "closedTime" STRING,
  "new" BOOLEAN,
  featured BOOLEAN,
  submitted_by STRING,
  archived BOOLEAN,
  "resolvedBy" STRING,
  restricted BOOLEAN,
  "groupItemTitle" STRING,
  "groupItemThreshold" STRING,
  "questionID" STRING,
  "umaEndDate" STRING,
  "enableOrderBook" BOOLEAN,
  "orderPriceMinTickSize" DOUBLE,
  "orderMinSize" BIGINT,
  "umaResolutionStatus" STRING,
  "volumeNum" DOUBLE,
  "liquidityNum" DOUBLE,
  "endDateIso" STRING,
  "startDateIso" STRING,
  "hasReviewedDates" BOOLEAN,
  "volume24hr" DOUBLE,
  "volume1wk" DOUBLE,
  "volume1mo" DOUBLE,
  "volume1yr" DOUBLE,
  "gameStartTime" STRING,
  "secondsDelay" BIGINT,
  "clobTokenIds" STRING,
  "umaBond" STRING,
  "umaReward" STRING,
  "volume24hrClob" DOUBLE,
  "volume1wkClob" DOUBLE,
  "volume1moClob" DOUBLE,
  "volume1yrClob" DOUBLE,
  "volumeClob" DOUBLE,
  "liquidityAmm" DOUBLE,
  "liquidityClob" DOUBLE,
  "makerBaseFee" BIGINT,
  "takerBaseFee" BIGINT,
  "customLiveness" BIGINT,
  "acceptingOrders" BOOLEAN,
  "negRisk" BOOLEAN,
  "negRiskRequestID" STRING,
  events ARRAY<STRUCT<
    id STRING,
    ticker STRING,
    slug STRING,
    title STRING,
    "description" STRING,
    "resolutionSource" STRING,
    "startDate" STRING,
    "creationDate" STRING,
    "endDate" STRING,
    image STRING,
    icon STRING,
    active BOOLEAN,
    closed BOOLEAN,
    archived BOOLEAN,
    "new" BOOLEAN,
    featured BOOLEAN,
    restricted BOOLEAN,
    liquidity DOUBLE,
    volume DOUBLE,
    "openInterest" DOUBLE,
    "createdAt" STRING,
    "updatedAt" STRING,
    competitive DOUBLE,
    "volume24hr" DOUBLE,
    "volume1wk" DOUBLE,
    "volume1mo" DOUBLE,
    "volume1yr" DOUBLE,
    "enableOrderBook" BOOLEAN,
    "liquidityAmm" DOUBLE,
    "liquidityClob" DOUBLE,
    "negRisk" BOOLEAN,
    "commentCount" BIGINT,
    series ARRAY<STRUCT<
      id STRING,
      ticker STRING,
      slug STRING,
      title STRING,
      "seriesType" STRING,
      recurrence STRING,
      image STRING,
      icon STRING,
      active BOOLEAN,
      closed BOOLEAN,
      archived BOOLEAN,
      "createdAt" STRING,
      "updatedAt" STRING,
      "volume24hr" DOUBLE,
      volume DOUBLE,
      liquidity DOUBLE,
      "commentCount" BIGINT,
      "requiresTranslation" BOOLEAN
    >>,
    cyom BOOLEAN,
    "closedTime" STRING,
    "showAllOutcomes" BOOLEAN,
    "showMarketImages" BOOLEAN,
    "automaticallyResolved" BOOLEAN,
    "enableNegRisk" BOOLEAN,
    "automaticallyActive" BOOLEAN,
    "eventDate" STRING,
    "startTime" STRING,
    "seriesSlug" STRING,
    score STRING,
    period STRING,
    live BOOLEAN,
    ended BOOLEAN,
    "finishedTimestamp" STRING,
    "negRiskAugmented" BOOLEAN,
    "pendingDeployment" BOOLEAN,
    deploying BOOLEAN,
    "gameId" BIGINT,
    "requiresTranslation" BOOLEAN,
    "eventMetadata" STRUCT<
      "context_description" STRING,
      "context_requires_regen" BOOLEAN,
      "context_updated_at" STRING,
      format STRING,
      league STRING
    >
  >>,
  ready BOOLEAN,
  funded BOOLEAN,
  "acceptingOrdersTimestamp" STRING,
  cyom BOOLEAN,
  competitive DOUBLE,
  "pagerDutyNotificationEnabled" BOOLEAN,
  approved BOOLEAN,
  "rewardsMinSize" DOUBLE,
  "rewardsMaxSpread" DOUBLE,
  spread DOUBLE,
  "automaticallyResolved" BOOLEAN,
  "oneHourPriceChange" DOUBLE,
  "oneDayPriceChange" DOUBLE,
  "lastTradePrice" DOUBLE,
  "bestAsk" DOUBLE,
  "automaticallyActive" BOOLEAN,
  "clearBookOnStart" BOOLEAN,
  "manualActivation" BOOLEAN,
  "negRiskOther" BOOLEAN,
  "sportsMarketType" STRING,
  line DOUBLE,
  "umaResolutionStatuses" STRING,
  "pendingDeployment" BOOLEAN,
  deploying BOOLEAN,
  "deployingTimestamp" STRING,
  "rfqEnabled" BOOLEAN,
  "holdingRewardsEnabled" BOOLEAN,
  "feesEnabled" BOOLEAN,
  "requiresTranslation" BOOLEAN,
  "feeType" STRING,
  "marketMetadata" STRUCT<
    "opticOddsFixtureId" STRING,
    "opticOddsMarketId" STRING,
    "opticOddsMarketName" STRING,
    "opticOddsPlayerId" STRING,
    "opticOddsPoints" DOUBLE,
    "opticOddsSelection" STRING,
    "opticOddsSelectionLine" STRING
  >,
  "feeSchedule" STRUCT<
    exponent BIGINT,
    rate DOUBLE,
    "takerOnly" BOOLEAN,
    "rebateRate" DOUBLE
  >,
  PRIMARY KEY ("conditionId")
) WITH (
  'store' = 'warpstream',
  'topic' = 'demo_pm_gamma_markets',
  'value.format' = 'json'
);

ALTER RELATION pm_gamma_markets_cl SET description =
'Raw Polymarket Gamma market changelog over warpstream topic demo_pm_gamma_markets. Primary key is conditionId from the Kafka message key/value payload.';
